//! `mehen-markdown` — Markdown documentation metrics analyzer.
//!
//! Per the rewrite plan §4.7 / §6.6 / §8.1, the pre-1.0
//! `src/markdown/**` analyzer was physically moved here intact. The
//! high-level entry point [`analyze_markdown`] retains its original
//! signature so existing fixtures and snapshot tests pass without
//! modification.
//!
//! The grammar kind enum (`grammar::Markdown`) is generated by
//! `cargo run -p enums -- --per-crate` per plan §6.7 — kind enums
//! become a private detail of the owning analyzer crate.
//!
//! Embedded-code analysis used to dispatch through
//! `crate::langs::get_function_spaces`. To avoid pulling that
//! macro-driven machinery into this crate, the legacy `mehen` library
//! supplies the embedded callback through
//! [`set_legacy_dispatch`]; a follow-up phase wires the
//! plan §4.7 `LanguageDispatcher` seam.

#![allow(clippy::upper_case_acronyms)]

mod analyzer;
mod artifact_debt;
mod code_burden;
pub mod diagrams;
mod dmi;
mod ecu;
mod embedded_code;
mod evidence;
mod filler;
mod good_scaffold;
mod grammar;
mod grounding;
mod halstead;
mod legacy_node;
mod links;
mod loc;
mod math_burden;
mod mathops;
mod mcc;
mod mrpc;
mod nearby;
pub mod prose;
mod rci;
mod section_balance;
mod sections;
mod tables;
pub mod types;
mod visuals;
mod words;

pub use analyzer::analyze_markdown;
pub use embedded_code::{EmbeddedFenceMetrics, FenceLanguage, set_legacy_dispatch};

use mehen_core::{
    AnalysisBackend, AnalysisConfig, Language, LanguageAnalysis, LanguageAnalyzer, MetricSpace,
    SourceFile, SourceSpan, SpaceId, SpaceKind, byte_offset_clamped,
};

/// Tree-sitter-backed Markdown analyzer for the engine registry.
///
/// The rich metric pipeline runs through [`analyze_markdown`] and
/// produces [`types::MarkdownMetrics`] (a Markdown-specific report
/// shape). The engine's `LanguageAnalyzer` integration ships an empty
/// `MetricSpace` here — phase-5 follow-up wires the rich Markdown
/// metrics into the diff JSON via `mehen-report`.
pub struct MarkdownAnalyzer;

impl MarkdownAnalyzer {
    pub fn new() -> Self {
        Self
    }
}

impl Default for MarkdownAnalyzer {
    fn default() -> Self {
        Self::new()
    }
}

impl LanguageAnalyzer for MarkdownAnalyzer {
    fn language(&self) -> Language {
        Language::Markdown
    }

    fn backend(&self) -> AnalysisBackend {
        AnalysisBackend::MarkdownLegacy
    }

    fn analyze(
        &self,
        source: &SourceFile,
        _config: &AnalysisConfig,
    ) -> mehen_core::Result<LanguageAnalysis> {
        let span = SourceSpan {
            start_byte: 0,
            end_byte: byte_offset_clamped(source.text.len()),
            start_line: 1,
            end_line: source.line_index.line_count(),
        };
        Ok(LanguageAnalysis {
            language: Language::Markdown,
            backend: AnalysisBackend::MarkdownLegacy,
            diagnostics: Vec::new(),
            root: MetricSpace::new(SpaceId(0), SpaceKind::Unit, span),
            contributions: Vec::new(),
        })
    }
}
