on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.rs'
      - '.github/workflows/lint.yml'
      - 'action.yml'
      - Cargo.lock
      - 'scripts/**/*.mjs'

permissions:
  contents: read
  pull-requests: write
  issues: write

name: Code Quality Checks

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: '-Dwarnings'
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust toolchain
        run: rustup show

      - name: Check GitHub Action script
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: node --test scripts/github-action.test.mjs

      - run: cargo clippy --workspace --all-targets --all-features --locked

      - run: cargo fmt --all --check

      - name: Spell Check Repo
        uses: crate-ci/typos@v1

      - name: Cargo Machete
        uses: bnjbvr/cargo-machete@7959c845782fed02ee69303126d4a12d64f1db18 # v0.9.1

      - name: Publish mehen metrics
        uses: ./
        with:
          install-method: cargo
          paths: src
